imports:
  - { resource: ../common.yml }

services:
    block_reassurance_form_data_handler:
        class: 'PrestaShop\Module\BlockReassurance\Form\PsreassuranceFormDataHandler'
        public: true
        arguments:
            - '@block_reassurance_repository'
            - '@prestashop.core.admin.lang.repository'
            - '@doctrine.orm.default_entity_manager'